### ISSUE TITLE
API calls fail when payload contains values with ampersands in them

### ISSUE THREAD

**Issue by anttiviljami** [Bynder/bynder-js-sdk#8]
Whenever I try to send any payload with a value with the letter "&" in it, I always get a 401 error saying my oauth signature is incorrect.

```
Error: Request failed with status code 401                                                                                                          
    at createError (/Users/akuo/bynder-js-sdk/node_modules/axios/lib/core/createError.js:16:15)                                                                                                                          
    at settle (/Users/akuo/bynder-js-sdk/node_modules/axios/lib/core/settle.js:18:12)                                                                                                                                    
    at IncomingMessage.handleStreamEnd (/Users/akuo/bynder-js-sdk/node_modules/axios/lib/adapters/http.js:201:11)                                                                                                        
    at emitNone (events.js:91:20)                                                                                                                                                                                        
    at IncomingMessage.emit (events.js:185:7)                                                                                                                                                                            
    at endReadableNT (_stream_readable.js:974:12)                                                                                                                                                                        
    at _combinedTickCallback (internal/process/next_tick.js:80:11)                                                                                                                                                       
    at process._tickCallback (internal/process/next_tick.js:104:9)                                                                                                                                                       message=Invalid signature, 
signatureBaseString=..., statuscode=401                        
```

**Comment by anttiviljami** [comment]
Looks like the problem is that ampersands don't get encoded in the payload. The fix is using `encodeURIComponent`, instead of `encodeURI` when generating the query string.

**Comment by GuilhermeSCP** [comment]
Do you want to create a PR for this repo as well?
